### ISSUE TITLE
issue with sub-properties when updating accounts with Accounts_Onboard_Utility v10

### ISSUE THREAD

**Issue by FIMTooler** [cyberark/epv-api-scripts#10]
It should also be noted that the secretManagement attribute will almost always attempt to update and fail.  This is a result of it's object type.  Sub-properties are not compared independently, but the entire value of the array shown below.  The PVWA will almost always return a matching object with some additional properties within secretManagement such as the lastModifiedTime shown below which in turn causes the comparison to not match.

sProp name: secretManagement
sProp value: @{automaticManagementEnabled=False; manualManagementReason=No Reason; lastModifiedTime=1544813950}
objAccount value: @{automaticManagementEnabled=False; manualManagementReason=No Reason}

When secretManagement is added to the $s_AccountBody, the value is an array and the path is "/secretManagement".  From what I've seen, each property should be specified in the path such as "/secretManagement/automaticManagementEnabled" and "/secretManagement/manualManagementReason" as separate changes.

**Comment by AssafMiron** [comment]
Script updated and fixed
