### ISSUE TITLE
Safe Management - PVWAURL Errors

### ISSUE THREAD

**Issue by Quirkcr** [cyberark/epv-api-scripts#102]
We are attempting to utilize the Safe Management Utility and receiving two different error messages when attempting to use two different PVWA URL's. 

URL 1: as stated in the ReadMe - PVWAURL "https://myPVWA.myDomain.com/PasswordVault"
Error Message: Cannot validate argument on parameter 'PVWAURL'. Unable to connect to remote server

URL 2: with addition on end - PVWAURL "https://myPVWA.myDomain.com/PasswordVault/v10/logon/Cyberark"
Steps: I enter the url 2 as mentioned above in the powershell script and am able to enter the Username and Password. See Error below.
Error Message: Logon Token is empty - Cannot logon.

**Comment by AssafMiron** [comment]
Hello @Quirkcr 

The first URL is the correct one to use
It could be that there is an SSL issue from the machine that you are running it from (for example, use of IP or un-recognized DNS, it could also be mismatching SSL options)
You can try running the script with -DisableSSLVerify and see if that solves the issue

Let me know if that works,
Assaf

**Comment by Quirkcr** [comment]
Hey Assaf, 

Thanks for reaching out. I did try the DisableSSLVerify command as well with no success. Can you think of any other troubleshooting methods? Our pvwa machines are load balanced. I have tried with the load balancer vip, server IP of both pvwas, and server names of both pvwas. All with the same issue. 

I checked the carts and they seem valid.

I also would like to note that the account onboarding utility worked for me. 

Thanks!
Christopher Quirk
m. 757-876-9866
https://www.linkedin.com/in/quirkcr/

**Comment by AssafMiron** [comment]
Hello @Quirkcr 
I recently updated the Safe Management script - could you please take the latest and try again?
Let me know if that solves the issue
Thanks,
Assaf

**Comment by AssafMiron** [comment]
Hello @Quirkcr 
Any updates?

**Comment by Quirkcr** [comment]
My apologies on the delay, I will test this this week.

Chris

**Comment by AssafMiron** [comment]
Hello @Quirkcr 
Any updates?

**Comment by bab29** [comment]
@Quirkcr Wanted to check with you to see if you still needed help with this or if it has been resolved.

If I don't hear anything by the 1st I will go ahead and close this.
