### ISSUE TITLE
Help Message Line 20

### ISSUE THREAD

**Issue by jjuette** [cyberark/epv-api-scripts#11]
`	[Parameter(Mandatory=$true,HelpMessage="Please enter your PVWA address (For example: https://pvwa.mydomain.com)")]`
should read `	[Parameter(Mandatory=$true,HelpMessage="Please enter your PVWA address (For example: https://pvwa.mydomain.com/passwordvault)")]`
to eliminate confusion.

**Comment by AssafMiron** [comment]
Thanks @jjuette will fox that
