### ISSUE TITLE
Export-Import-Platform.ps1 - "Logon Token is Empty - Cannot Login"

### ISSUE THREAD

**Issue by Jayk423** [cyberark/epv-api-scripts#115]
Line 125 needs to be updated to read: 

$logonHeader.Add("Authorization",$logonToken.**CyberArkLogonResult**)

Thanks!
Jake

**Comment by Jayk423** [comment]
This is actually 1st Gen vs. 2nd Gen related: https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/SDK/CyberArk%20Authentication%20-%20Logon_v10.htm

1st gen authenetication returns the logon token inside of the CyberArkLogonResult property of the result. 2nd Gen does not.

**Comment by AssafMiron** [comment]
Hi @Jayk423 
Seems like this is resolved
Can this issue be closed?
