### ISSUE TITLE
Needing to force TLS 1.2 after running PVWA Hardening script

### ISSUE THREAD

**Issue by seswho** [cyberark/epv-api-scripts#12]
Hello Assaf,

Found the following line needs to be added to the script to force the use of TLS 1.2 in PowerShell: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

The section of code testing to see if SSL verification should be disabled does not set the use of any TLS. The PVWA hardening script and manual process disables all versions of SSL and TLS other than 1.2.

**Comment by AssafMiron** [comment]
Hi @seswho ,

Can you describe where does it fail for you?
Is it after the PVWA URL validation?
Why are you running it with DisableSSL switch?

Thanks,
Assaf

**Comment by AssafMiron** [comment]
Hi @seswho ,

I added the support to use TLS 1.2, can you please verify that it works for you now

Thanks,
Assaf
