### ISSUE TITLE
Update password?

### ISSUE THREAD

**Issue by jrsy25** [cyberark/epv-api-scripts#120]
Hi,  Can this be used to update password? I tried but it appears to be not working

**Comment by AssafMiron** [comment]
Hello @jrsy25 
To what script are you referring to?
There is the Account Onboarding tool script that can update password
If you are using for example this command"
& .\Accounts_Onboard_Utility.ps1 -PVWAURL "https://myPVWA.myDomain.com/PasswordVault" -CsvPath .\accounts.csv -Update -NoSafeCreation

and in the accounts.csv there is the account details that you want to update and the column of 'password' then it will try to update the password of that account.
You can run the script with -Debug -Verbose to see extra logging on all actions in the log file

Here is a link to the script:
https://github.com/cyberark/epv-api-scripts/tree/master/Account%20Onboard%20Utility

Regards,
Assaf

**Comment by jrsy25** [comment]
Sorry it took a while to get back to you and yes it is working. Thanks a lot!!!!
