### ISSUE TITLE
AOU - Errors when attempting to onboard accounts

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/epv-api-scripts#125]
**When attempting to onboard accounts the following error is being seen:**

```
Error Message: {"Details":[{"ParameterName":"remoteMachinesAccess.accessRestrictedToRemoteMachines","ErrorCode":"PASWS168E","ErrorMessage":"Input parameter for [remoteMachinesAccess.accessRestrictedToRemoteMachines] value is 
invalid"}],"ErrorCode":"PASWS167E","ErrorMessage":"There are some invalid parameters"}
Exception Message: The remote server returned an error: (400) Bad Request.
Status Code: 400
Status Description: Bad Request
```

**My CSV has the following:**
```
username,address,safe,platformID,password,EnableAutoMgmt,ManualMgmtReason
AOU-User014,Target011.south.local,_AOU-NewSafe001,AOU-WinServers001,kS$47.po,Yes,,
```

**When I comment out the following lines I do not get the error:**

```
#	$_Account.remoteMachinesAccess = "" | select "remoteMachines", "accessRestrictedToRemoteMachines"
#	$_Account.remoteMachinesAccess.remoteMachines = $AccountLine.remoteMachineAddresses
#	$_Account.remoteMachinesAccess.accessRestrictedToRemoteMachines = Convert-ToBool $AccountLine.restrictMachineAccessToList
```

However by doing this I believe I possibly causing other issues which I am currently working through, I am not quite sure how to work around this issue currently. I have tried to add additional FC's in to the CSV with no luck.

**Comment by NathTheDude** [comment]
As another test, I used the following CSV which worked on a AOU version from March 2020 however I get the error that I mentioned when using this CSV with the latest version of AOU:

```
username,address,safe,platformID,password,EnableAutoMgmt,ManualMgmtReason,RemoteMachineAddresses,RestrictMachineAccessToList,AOU-TestProperty001,AOU-TestProperty002
AOU-User023,Target002.south.local,_AOU-NewSafe001,AOU-WinServers001,kS$47.po,Yes,,,TestComment001,TestComment2
```

**Comment by AssafMiron** [comment]
Hey @NathTheDude 
I think the reason is that the accessRestrictedToRemoteMachines and it expects to be Bool
I think a solution for that could be checking if remoteMachines is null then not try to set the accessRestrictedToRemoteMachines 
Do you mind giving that a try?

**Comment by NathTheDude** [comment]
Thanks, that fixed it. I'll update and add a pull for you to review.
