### ISSUE TITLE
Feature Request - Standardize AuthType

### ISSUE THREAD

**Issue by tarheeljeff** [cyberark/epv-api-scripts#128]
I think it would be beneficial to add the '-AuthType' option to all scripts in a standardized way.   The way it is done in the Account Onboarding scripts seems perfect.

It would be ideal if 'CyberArk' were the default for all scripts, but with the option to pass other -AuthType options.   

Example:  I am doing some testing with the Safe Management scripts in a development environment and it doesn't allow Radius auth type, which is needed.

**Comment by AssafMiron** [comment]
Hello @tarheeljeff ,

Thanks for proposing this enhancement request, I will shortly update it for the scripts that were missing it.
Specifically for the Safe Management script is using the 1st generation logon API I have updated the README file to include a tip on how to authenticate also using LDAP in addition to CyberArk without even changing the script :)

Let me know what you think

Regards,
Assaf
