### ISSUE TITLE
Unable to create or update an account with custom properties

### ISSUE THREAD

**Issue by seswho** [cyberark/epv-api-scripts#13]
Hello Assaf,

While running the script, a customer and I have found the script will not create any custom properties for an account.

The customer is wanting to add LognnDomain, ExtraPass3Folder, ExtraPass3Name, and ExtraPass3Folder properties. 

In my lab, running the script without the extra properties, the account would be created properly. If I tried to run the script to create the account with the extra properties throws an error "Bad Request." I've included the verbose output from the script (removed the password and token values) in the attached text document and the .csv file I used and from the customer.

[gl-csat-account1-corptest.txt](https://github.com/cyberark/epv-api-scripts/files/2870709/gl-csat-account1-corptest.txt)
[gl-csat-account1-corptest-update.txt](https://github.com/cyberark/epv-api-scripts/files/2870710/gl-csat-account1-corptest-update.txt)
[aou_verbose_txt.txt](https://github.com/cyberark/epv-api-scripts/files/2870696/aou_verbose_txt.txt)

**Comment by AssafMiron** [comment]
Hi @seswho ,

THe ExtraPass parameters are not supported as custom properties
this is basically a different ability for linked accounts (Reconcile and Logon)
LogonDomain should be supported, can you run the same with just the Logon domain and see if it fails?

Thanks,
Assaf
