### ISSUE TITLE
Import-ConnectionComponents -ConnectionComponentFolderPath does not work

### ISSUE THREAD

**Issue by godlyfrog** [cyberark/epv-api-scripts#132]
Tested and resolved in Powershell 5.1.  The issue is in line 176: Get-ChildItem results in a string which contains a header the filename with file path.  When it is later parsed by line 191, it fails to properly test the paths.  This can be corrected by changing the line from:

$arrConCompToImport += (Get-ChildItem -Path $ConnectionComponentFolderPath -Filter "*.zip")

To

$arrConCompToImport += (Get-ChildItem -Path $ConnectionComponentFolderPath -Filter "*.zip" | Select-Object -ExpandProperty FullName)

**Comment by AssafMiron** [comment]
Thanks a lot @godlyfrog 
I added your suggestion - Thanks!
