### ISSUE TITLE
Safe-Management - using CSV to update safe's

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/epv-api-scripts#135]
For my usecase I am trying to change the CPM that manages a couple safes, so I am using a csv for this only contains 1) the safe name, and 2) ManagingCPM.

When only using two two values in a one liner I am able to update the single safe but when I try to do this from a csv this is working, it looks like the script is assuming that I want to update the members of the safe. As there are no columns/headers in the csv for these fields a default value of 'False' is being used.

As values are now entered in for these permission fields when the call is made back to the vault it now also expects the 'MemberName' to be part of the call as we have included information about the permissions that need to be set.

Ideally when importing the csv and setting values, if the 'MemberName' is empty them the other values should be ignored. and not added to the call with default values.

**Comment by AssafMiron** [comment]
Thanks for the info @NathTheDude 
I have updated the script in the Debug branch for you to test again (see the commit reference above)
Could you please let me know if it works?

Thanks,
Assaf

**Comment by NathTheDude** [comment]
@AssafMiron thanks, thats great.

This line just needs to be updated from:
numVersionRetention==$line.numVersionRetention;
to
numVersionRetention=$line.numVersionRetention;

**Comment by AssafMiron** [comment]
Thanks a lot @NathTheDude 
Did the change and merged to main :)

Thanks again!
