### ISSUE TITLE
Would like the ability to import accounts with Password History - KeePass export to XML

### ISSUE THREAD

**Issue by PSingletary** [cyberark/epv-api-scripts#14]
We have a number of accounts stored in KeePass. Exporting to CSV and using Accounts_Onboard_Utility.ps1 has be great. We have run into an issue where there are some accounts that we would like to maintain the password history. KeePass offers a XML export that includes the password history.

1. Do the rest APIs support importing an account's Password History?
1.  Is there any future plans for accepting XML input?

**Comment by AssafMiron** [comment]
Hi @PSingletary ,
Thanks for your feedback, this is a great idea
Although currently we do not have Password History REST API, maybe we can do "Update Password" for every password of that account (from the oldest to the newest) given the PAS password retention (by default by version) then you will have the same password history
WDYT?
