### ISSUE TITLE
Error when running Get-InactiveUsersReport.ps1 on master

### ISSUE THREAD

**Issue by metalwerks7** [cyberark/epv-api-scripts#149]
While running the Get-InactiveUsersReport.ps1
The function that shows this error is Get-LogonHeader
```
->Source:System.Management.Automation; Message: Cannot convert 'System.Object[]' to the type 'System.Collections.IDictionary' required by parameter 'Headers'. Specified method is not supported.
->Source:System.Management.Automation; Message: Specified method is not supported.
```
### Powershell Version
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
### CyberArkVersion
```
11.1
```
### Reproduction Steps:
run this script .\get-inactiveUsersReport.ps1 -pvwaurl https://yourpvwa/PasswordVault

**Comment by AssafMiron** [comment]
Thanks for you comment and info @metalwerks7 
I pushed a new version to the Debug branch to try and solve the issue
It would be good if you could run that new version with the -Debug -Verbose switches and review/share the output log that should contain more details.
I think it might be related to the type of dictionary that I'm using that PowerShell 5 might not like, if that is the case we can try running powershell with the switch of Version
For example: Powershell.exe -Version 3

Let me know how it goes

Thanks,
Assaf

**Comment by AssafMiron** [comment]
Hi @metalwerks7 ,
The script was tested and merged to main
Would be good to know if that resolved your issue
Thanks,
Assaf

**Comment by metalwerks7** [comment]
Hi Assaf,

Thank you for making the changes. The error went away, however I get this error 401 now. I have tried with local cyberark account and radius ldap account without any luck. Let me know what I can do to get pass this error. Thank you once again. 

`Starting script (v1.0)
Creating a list of all inactive users from the last 30 days
Exception Message: The remote server returned an error: (401) Unauthorized.
Status Code: 401
Status Description: Unauthorized
Generating report
Logoff Session...`

**Comment by AssafMiron** [comment]
Hi @metalwerks7 ,
Please note that you need to have version 10.9 or above of PVWA and that the user you are logging in with should have the "Audit Users" Vault authorization

**Comment by bab29** [comment]
@metalwerks7 

Wanted to confirm this can be closed. Thanks
