### ISSUE TITLE
Get adhoc access script is not working

### ISSUE THREAD

**Issue by uniqueperformtechsoft** [cyberark/epv-api-scripts#15]
Hi,

When I try to run the utility get adhoc access we are getting the following error. I have set the power shell execution policy to unrestricted. please find the below error details for your review.

PS C:\CyberarkScripts> .\Get-AdHocAccess.ps1

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\CyberarkScripts\Get-AdHocAccess.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
At C:\CyberarkScripts\Get-AdHocAccess.ps1:143 char:19
+               Sign&nbsp;up
+                   ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:170 char:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:170 char:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:184 char:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:184 char:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:185 char:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:185 char:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:205 char:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:205 char:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\CyberarkScripts\Get-AdHocAccess.ps1:208 char:107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

Thanks & Regards
Karthik Raja

**Comment by pspete** [comment]
I think this is related to copy/pasting the code from GitHub - there appears to be HTML artifacts causing you issues.
If you are unable to clone/download the repository to your local machine, try to copy/paste the code from here: https://raw.githubusercontent.com/cyberark/epv-api-scripts/master/PSM%20Sessions%20Management/Get-AdHocAccess.ps1
