### ISSUE TITLE
Update-Account.ps1 modification

### ISSUE THREAD

**Issue by MisterW01f** [cyberark/epv-api-scripts#151]
We had an issue where when we try to set LogonDomain to an existing account that doesn't have that property already setup, we can't add it as the replace doesn't work.

I've modified the Update-Account.ps1 with those pieces of code:
Line 148:
```
#Start Modification#
if ($([string]::IsNullOrEmpty($GetAccountDetailsResponse.platformAccountProperties)))
{
	$PropsName = @()
}
else
{
	$PropsName = Get-Member -InputObject $GetAccountDetailsResponse.platformAccountProperties -MemberType NoteProperty | foreach { $_.Name }
}
#End Modification#
```
Line 194:
```
#Start Modification#
if ($PropsName.Contains($param.Name))
{
	$_bodyOp.op = "replace"
} else {
	$_bodyOp.op = "add"
}
#End Modification#
```
I included my modified file
[Update-Account-Modified.ps1.txt](https://github.com/cyberark/epv-api-scripts/files/5568634/Update-Account-Modified.ps1.txt)

**Comment by AssafMiron** [comment]
Thanks a lot @MisterW01f 
I will add it to the next push
