### ISSUE TITLE
Getting error while trying to execute safemanegent.ps1 to create safe 

### ISSUE THREAD

**Issue by amitgautam1990** [cyberark/epv-api-scripts#154]
Getting error while trying to execute safemanegent.ps1 to create safe 

Cannot validate argument on
parameter 'PVWAURL'. The underlying connection was closed: An unexpected error occurred on a send.

**Comment by AssafMiron** [comment]
Hi @amitgautam1990 ,
Try running the script using -DisableSSLVerify
That usually helps resolve this error

**Comment by AssafMiron** [comment]
@amitgautam1990  any feedback? can we close this issue?

**Comment by yuqaili** [comment]
Hi @AssafMiron 

I also ran into the similar issue, Cannot validate argument on
parameter 'PVWAURL'. The underlying connection was closed: An unexpected error occurred on a send.

also tried the suggestion using -DisableSSLVerify
still No Luck 
[RestError.pdf](https://github.com/cyberark/epv-api-scripts/files/6672946/RestError.pdf)

I did successfully ran all these scripts 2 days ago from the same server and created safes, added members and bulk on-boarded accounts. 

please advise.

**Comment by AssafMiron** [comment]
Hi @yuqaili ,
Thanks for the update, great solution
one other option would be to comment out line 22 that tries to validate the parameter of PVWA URL:
[ValidateScript({Invoke-WebRequest -UseBasicParsing -DisableKeepAlive -Uri $_ -Method 'Head' -ErrorAction 'stop' -TimeoutSec 30})]
This validation happens without your suggested lines and thus TLS negotiation fails
I will try to see if I can add your suggestion as part of the validation in the script

Thanks again for the update,
Assaf
