### ISSUE TITLE
Questionable timeout setting

### ISSUE THREAD

**Issue by jeffrechten** [cyberark/epv-api-scripts#157]
https://github.com/cyberark/epv-api-scripts/blob/411d00af4f3718a93d77a8ccc1e7885d2e87cd5b/Safe%20Management/Safe-Management.ps1#L329

@AssafMiron any thoughts on why this timeout is set so high? 
41 days seems too long to me unless I'm missing something really important.

**Comment by AssafMiron** [comment]
Hey @jeffrechten,

The main reason for the long timeout is to better handle situations of
network lags and slow TLS handshakes that sometimes happen.
It doesn't have a lot of affect in case the logon succeeds, then it returns
immediately and the timeout does not take affect
The long timeout is also relevant for heavy commands like Get Safes where
we have witnessed for large environments it could take some time to get the
complete list of all safes (sometimes even 2 minutes or more) so the long
timeout is required

Hope it makes sense
Regards,
Assaf

**Comment by AssafMiron** [comment]
@jeffrechten I agree though that 41 days is an exaggeration 😄 
I will work on reducing it to a maximum of 45 minutes (this is the highest I heard someone had to use until getting a response back)
