### ISSUE TITLE
Get-InactiveUsersReport.ps1 reports all users regardless the InactiveDays value specified

### ISSUE THREAD

**Issue by Francesco-f7o** [cyberark/epv-api-scripts#165]
## Summary
Get-InactiveUsersReport.ps1 reports all users regardless the InactiveDays value specified

## Expected Results
Running the Get-InactiveUsersReport.ps1script with a set number of inactive days, or even leaving the default 30 days, returns all users instead of listing only the inactive ones.

## Actual Results (including error logs, if applicable)
The output CSV includes all the users in the deployment, not just the active ones.
Although this is easily filteres in the output file, it doesn't seem to match what is says in the readme.
It could be just a matter of claryfing what to expect in the readme.

InactiveDays
The number of days to check for inactivity of users
Default value: 30 days

## Reproducible
   [*] Always 
   [ ] Sometimes
   [ ] Non-Reproducible

## Version/Tag number
Issue reproduced downloading the script on the 9th of February 2021 against an 11.7 environment.

## Command used to extract the report
.\Get-InactiveUsersReport.ps1 -PVWAURL https://PVWAURL/PasswordVault -InactiveDays 90 -CSVPath InactiveUsers.csv -Verbose

**Comment by AssafMiron** [comment]
Hi @Francesco-f7o ,
Thanks for letting us know, this was now fixed in the new version of the script
