### ISSUE TITLE
Get-InactiveUsersReport.ps1 returns a mixture of date formats for the LastSuccessfulLoginDate field

### ISSUE THREAD

**Issue by Francesco-f7o** [cyberark/epv-api-scripts#166]
## Summary
Get-InactiveUsersReport.ps1 returns a mixture of date formats for the LastSuccessfulLoginDate field.

Some users have this field in a mm/dd/aaaa HH:MM format (using a 24h format).
Other users have a mm/dd/aaaa hh:mm AM/PM format (using a 12h format).

Examples:
"PVWAAppUser","","","CyberArk","PVWA","True","True","False","12/3/2020 10:09:05 AM","AddSafes;AuditUsers"
"assafmiron@cybrlab.local","","","CyberArk","EPVUser","False","True","False","12/2/2020 1:22:38

## Steps to Reproduce
1. Run Get-InactiveUsersReport.ps1 against an 11.1+ environment
2. Review the LastSuccessfulLoginDate data

## Expected Results
All LastSuccessfulLoginDate are listed using the same format

## Actual Results (including error logs, if applicable)
Dates are reported using a mixture of formats

## Reproducible
   [*] Always 
   [ ] Sometimes
   [ ] Non-Reproducible
   
## Version/Tag number
Get-InactiveUsersReport.ps1 downlaoded the 9th of February 2021, against an 11.7 environment.

## Command used to extract the report
.\Get-InactiveUsersReport.ps1 -PVWAURL https://PVWAURL/PasswordVault -InactiveDays 90 -CSVPath InactiveUsers.csv -Verbose

**Comment by AssafMiron** [comment]
Hi @Francesco-f7o ,
Thanks for letting us know, this was now fixed in the new version of the script
I used a constant date time format for all dates (yyyy-mm-dd hh:mm:ss)
