### ISSUE TITLE
Is it possible to to query 1 user's safe membership using rest api?

### ISSUE THREAD

**Issue by engkeen-source** [cyberark/epv-api-scripts#172]
I had look through rest api cyberark documentation and unable to find on how to query 1 user' safe membership. 

For example user A is safe member of 10 safe.  I want to find all these 10 safe and respective safe permission based on this 10 safe.

Currently what Im doing is export all safe membership using evd and import to excel and query using vba. 

and Im planing to use vba to call rest api and direct query. Is there any way can help?

**Comment by AssafMiron** [comment]
Hello @engkeen-source ,
Currently there is no way to get this information using REST API 
There is a PACLI command to get you exactly what you are looking for (OwnerSafesList):
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PACLI/Safe-Functions.htm#OwnerSafesList

If you need this as a REST, I recommend opening  an enhancement request

Hope this helps,
Assaf
