### ISSUE TITLE
Get Safe members unable to filter by includePredefinedUsers eq false

### ISSUE THREAD

**Issue by engkeen-source** [cyberark/epv-api-scripts#177]
I trigger web api request, return is 200 ok, but the result include predefined user such as master, dr etc.
As refer by CyberArk Doc.
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/SDK/Safe%20Members%20WS%20-%20List%20Safe%20Members.htm?tocpath=Developer%7CREST%20APIs%7CSafes%7CSafe%20members%7C_____1

http://xxxxxx.com.sg/PasswordVault/api/Safes/TESTSAFE2222/Members/?filter=includePredefinedUsers eq false

I tried several URL below, all result returned include predefined user.
http://xxxxxx.com.sg/PasswordVault/api/Safes/TESTSAFE2222/Members/?filter=includePredefinedUserseqfalse
http://xxxxxx.com.sg/PasswordVault/api/Safes/TESTSAFE2222/Members/?filter=includePredefinedUsers=false
http://xxxxxx.com.sg/PasswordVault/api/Safes/TESTSAFE2222/Members/?filter=includePredefinedUsers

Is the URL correct?

**Comment by AssafMiron** [comment]
The default for includePredefinedUsers is false, so maybe you should not
include it
The URL has a redundant '/' after the Members
This should work:
http://<IIS_Server_Ip>/PasswordVault/api/Safes/{SafeUrlId}/Members?filter=includePredefinedUsers
eq false

Let me know if it works for you

Regards,
Assaf

**Comment by engkeen-source** [comment]
![image](https://user-images.githubusercontent.com/71132168/110717446-0ba9da80-8244-11eb-94dc-d7b8222a4b99.jpeg)![image](https://user-images.githubusercontent.com/71132168/110717447-0c427100-8244-11eb-8137-444df4ee11d0.jpeg)

Its still return predefined user for the correct URL I input

**Comment by AssafMiron** [comment]
And if you are not using this parameter? This should default to the same
thing

In anyway I would recommend opening a support case with CyberArk asking
them about this behavior
