### ISSUE TITLE
Something wrong with the parameters

### ISSUE THREAD

**Issue by kennywood** [cyberark/epv-api-scripts#185]
## Actual Results (including error logs, if applicable)
At C:\CyberArk\Account Onboard Utility\Accounts_Onboard_Utility.ps1:14 char:1
+ [CmdletBinding(DefaultParametersetName="")]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected attribute 'CmdletBinding'.
At C:\CyberArk\Account Onboard Utility\Accounts_Onboard_Utility.ps1:15 char:1
+ param
+ ~~~~~
Unexpected token 'param' in expression or statement.
At C:\CyberArk\Account Onboard Utility\Accounts_Onboard_Utility.ps1:24 char:20
+     [String]$AuthType="cyberark",
+                       ~~~~~~~~~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept
assignments, such as a variable or a property.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedAttribute

## Reproducible
   * [ ] Always 

## Version/Tag number
2.8

## Environment setup
Windows 10
PS 5.1.18362.1171

**Comment by tarheeljeff** [comment]
I am seeing similar.  I get an immediate error when I pass the '-Update' parameter ('-Create' runs fine)

**Comment by AssafMiron** [comment]
Thanks for the update
If you change the reported line to:
[CmdletBinding()]

Does it solve the problem?

**Comment by kennywood** [comment]
No, same errors, 

If I make it [CmdletBinding] and remove line 15 'param'. The first two errors go away. Just leaves something wrong with presetting $AuthType. 
Removing the default value of $AuthType gets rid of the last Parameters error, but  it appears as if the URL now gets called "comma" instead of the URL provided by $PVWAURL.
I debugged the code and saw that regardless of my input, $PVWAURL had a value of comma.

A little more research and I found the issue; sort of.
You either have a hidden ascii character in your header comment, or one of the # is not really a #:
#########################################################################
#
# NAME: Accounts Onboard Utility
#
# AUTHOR:  Assaf Miron
#
# COMMENT: 
# This script will onboard all accounts from a CSV file using REST API
#
# SUPPORTED VERSIONS:
# CyberArk PVWA v10.4 and above
#
###########################################################################

By comment blocking this whole section '<##>' I am able to run the script successfully.

**Comment by AssafMiron** [comment]
Thanks for checking
I will check it out and let you know
If you can use the script in the meanwhile that is at least good news
