### ISSUE TITLE
Warning while adding

### ISSUE THREAD

**Issue by Ananthhub** [cyberark/epv-api-scripts#2]
Dear Author,

I would like to say "Much Thanks" for your wonderful contribution.

While onboarding using the below script,

& .\Accounts_Onboard_Utility.ps1 -PVWAURL "http://X.X.X.X/PasswordVault"  -CsvPath .\accounts1.csv -Create -NoSafeCreation

I am getting Warning message, but it is added successfully in the safe.

WARNING: The Account Exists, Creating the same account twice will cause duplications

**Comment by AssafMiron** [comment]
Hello @Ananthhub ,

Thanks for letting us know about this issue.
Are you using the latest version of the script?
This message will show if we find a similar account already onboarded to the Vault. In order not to create duplications, we show this Warning message.
There was a bug in previous versions that searched the account only by user name and not address, the latest version includes this fix.
I would appreciate if you could let me know if that is not the case for you so we can know what to fix

Thanks,
Assaf

**Comment by Ananthhub** [comment]
Hi Assaf,

Thanks for your inputs.

I am using the latest version of the script. In that Safe, no accounts were onboarded earlier.

But, still I able to see the Warning message.

Thanks,
Ananth R S

**Comment by AssafMiron** [comment]
Thanks @Ananthhub ,
I would run the script in Verbose mode (just add -Verbose at the end of the command) and then you will be able to see all the responses from the server and understand why the script thinks that there is a duplicate account. 
I am keeping this issue open to hear from you if you find anything interesting that could help us fix this issue

Thanks,
Assaf
