### ISSUE TITLE
Safe Management variable mismatch.

### ISSUE THREAD

**Issue by couldberunning** [cyberark/epv-api-scripts#20]
In the safe management ps1 the following has a misspelling for NumberOfVersionsRetention

 "NumberOfVersionsRtention"=$updateRetVersions;

This does not result in an error in the script but it cannot be set via the add command safe and with either go to your default value or will select Numberofretention days instead.  

I add the e in my local code and it resolved.

**Comment by couldberunning** [comment]
line 288 is one example of this occurrence.

            "NumberOfVersionsRtention"=$numVersionRetention;

**Comment by AssafMiron** [comment]
Thanks a lot for reporting on this @couldberunning 
I updated the script
