### ISSUE TITLE
Can't update accounts using -Update parameter

### ISSUE THREAD

**Issue by captainfalcon23** [cyberark/epv-api-scripts#202]
When ever I try to use update command to update an existing account to associate reconcile account (or even add notes or anything) I am getting below error:
------------------------------------
Getting PVWA Credentials to start Onboarding Accounts
------------------------------------
Starting to Onboard 1 accounts
Safe XXX exists
Account XXX@XXX.com.au exist
**No Account updates detected - Skipping**
Logoff Session...

Vaulted 0 out of 1 accounts successfully.
=======================================
LogoffUrl
---------

Is there some syntax issue in my csv? It is based on the example given:
name,username,address,safe,Notes,ExtraPass3Folder,ExtraPass3Name,ExtraPass3Safe

Do we specifically need to follow the steps here, even if adding recon/logon account works fine in the UI? https://cyberark-customers.force.com/s/article/Add-Reconcile-and-Login-Accounts-to-an-Account-using-V10-REST-API

**Comment by AssafMiron** [comment]
Hi @captainfalcon23 ,

In order to update the linked accounts, at the moment you need to use the follow the steps as described here:
https://cyberark-customers.force.com/s/article/Add-Reconcile-and-Login-Accounts-to-an-Account-using-V10-REST-API

We are planning to add support of the newly released Linked accounts REST API
But that would be relevant only for supporting versions

Regards,
Assaf

**Comment by captainfalcon23** [comment]
Hi @AssafMiron 

Thanks - I got it working using -create option and following steps in mentioned article. However, when using the -Update flag, no matter the attrivute I try to add, I always get the error:

**No Account updates detected - Skipping**

Is the syntax of my CSV file correct for update? Even to add notes etc?

**Comment by AssafMiron** [comment]
Can you share your CSV file (using bogus details of course)

**Comment by captainfalcon23** [comment]
This is it: 

![image](https://user-images.githubusercontent.com/66669505/129284954-e588b40a-15b1-479d-8994-a8d461972ba5.png)

**Comment by bab29** [comment]
@captainfalcon23 

I want to confirm that this issue has been resolved and this can be closed. Thanks

**Comment by captainfalcon23** [comment]
> 

Hello, no it never got resolved. Issue is no matter what is in the csv, the accounts never get updated and always get skipped.

**Comment by bab29** [comment]
Are the fields you are trying to update extrapass fields or other fields?

**Comment by captainfalcon23** [comment]
Other fields. Does it work for you? Can you share example csv?

**Comment by bab29** [comment]
I will review the latest version and get back to you but it should.

**Comment by bab29** [comment]
A new version has been released that should solve this issue. Please try again.
