### ISSUE TITLE
12.2 API

### ISSUE THREAD

**Issue by RussKing146** [cyberark/epv-api-scripts#209]
Hey,

Am I right in thinking this wont work currently on version 12.2 as the URL and permissions have changed to the new generation of API

Thanks

Russ

**Comment by AssafMiron** [comment]
Hi Russ,

Looking at the latest docs, it is still listed (you can see 2nd generation
API and 1st generation API)
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/WebServices/Add%20Safe.htm?tocpath=Developer%7CREST%20APIs%7CSafes%7C_____1

What do you mean it is no longer listed?

Regards,
Assaf

**Comment by RussKing146** [comment]
Hi Assaf,

its the Add member portion I am referring too:

https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/WebServices/Add%20Safe%20Member.htm?tocpath=Developer%7CREST%20APIs%7CSafes%7CSafe%20members%7C_____1

No gen 1 API listed and the permissions are slightly different:

"requestsAuthorizationLevel1": false,
"requestsAuthorizationLevel2": false

instead of 

"requestsAuthorizationLevel": 0/1/2

in the epv-api-scripts the add member portion is still working on the Gen 1 api available up to version 12.0 but not beyond. 

thanks

Russ

**Comment by AssafMiron** [comment]
Thanks for this info @RussKing146
I checked internally and these REST API might not appear in the docs now
(maybe a miss that will be fixed) but they should still work
You can see here in the release notes of the latest version the list of
REST API that will not be available starting next version:
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/Release%20Notes/RN-WhatsNew12-2.htm?tocpath=Get%20Started%7CWhat%E2%80%99s%20New%7CRelease%20Notes%7C_____1#!#Platformendofsupport

By then I hope I will have time to change the script to use all new REST
APIs

Regards,
Assaf

**Comment by bab29** [comment]
@RussKing146 

I wanted to check if you are still having issues or if we can go ahead and close this.
