### ISSUE TITLE
Issue with Safe-Management.ps1: 404 error for certain Safename inputs

### ISSUE THREAD

**Issue by jack6177733651** [cyberark/epv-api-scripts#21]
I'm currently testing bulk upload of safes with Safe-Management.ps1 and encountered a problem. My input for the script is a comma delimited csv file in the format of safes-sample.csv and the command is ".\Safe-Management.ps1 -url 'pvwa url' -add -FilePath 'csv input' ". 

The script encounters a 404 error with any rows in the csv file where the "Safename" contains a white space, such as "Test Safe". Safe creation seems to work as I can verify in the pvwa that the safe was created with the correct name. However setting safe membership produces a "404 - File or directory not found." error. 

The issue seems to have some relations with the Encode-URL function, specifically line 137 "return [System.Web.HttpUtility]::UrlEncode($sText)", as when I replaced it with "return [uri]::EscapeDataString($sText)" in my local code the 404 error disappeared.

**Comment by AssafMiron** [comment]
Thanks for letting me know @jack6177733651 
Apparently there is quite a difference between the two methods and [uri]::EscapeDataString is more recommended :)
I have updated the scripts and added a small performance improvement there as well

Thanks!
