### ISSUE TITLE
AOU - If an account is already created, currently it can be time consuming to resolve

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/epv-api-scripts#215]
## Is your feature request related to a problem? Please describe.

Currently when onboarding accounts, if an account is found already onboarded then the options currently are:

Continue with Operation:
Yes, Yes to All, Halt Command, Suspend

## Describe the solution you would like

There are two solutions which could be put in place:
1) Add in an extra option when running the script (instead of for using '-add') to go through all the accounts in the csv and do a check in the vault to see if they already exists. Perhaps '-verify' option.

2) Extra options should be added which allow to 'skip/ignore' the individual account and 'skip/ignore all' for multiple accounts without being re-prompted. 

This will save the extra effort to having to go in to the csv and delete the accounts, for example if we are onboarding 200 accounts and there are 10 duplicates spread across this csv. We have to run the AOU 11 times, update the CSV 10 times to get the accounts onboarded.

## Describe alternatives you have considered

Not another option within the AOU script

**Comment by NathTheDude** [comment]
Hey @AssafMiron , not sure if an following the items uodated/mentioned in #212 but adding something along the lines of a 'whatif' would be great to see the expected results of running AOU before running it to cresye/update the safes/accounts.

**Comment by bab29** [comment]
@NathTheDude 

Wanted to check and see if your issue was resolved with the #212 update. Thanks
