### ISSUE TITLE
$tmpAccountName in accounts onboard script is used but not declared

### ISSUE THREAD

**Issue by akgitrokz** [cyberark/epv-api-scripts#220]
## Summary
$tmpAccountName in accounts onboard script is used but not declared leading to empty account name in logs and screen displayed message

looks like below:
[2021-12-09 01:13:16]	[INFO]	[2/2] Added  successfully.

**Comment by AssafMiron** [comment]
Thanks @akgitrokz 
We changed to a different parameter and obviously forgot to change this one
Thanks for letting us know
This will be fixed shortly
