### ISSUE TITLE
Unable to update account with a new FC value

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/epv-api-scripts#223]
When using AOU with the '-update' parameter, when it does the search for the existing account it pulls back the existing FC's that are associated with the account. If a new FC is included in the update (the account did not previously have a value for this FC) then it will not update it as it does not have anything to compare with.

Is it possible to update this so that values for new FC's can be account to an account?

For example, we are using the FC 'Location'. Currently we need to update mutiple accounts that did not previously have a value for this FC, although this is not possible using AOU currently. Only way for this to work is to put a fake value in for the 'Location' for each account but if we do that we might as well update it with the correct value.

**Comment by bab29** [comment]
No response received
