### ISSUE TITLE
Safe Does not exist

### ISSUE THREAD

**Issue by GameChanger912** [cyberark/epv-api-scripts#224]
I am trying to run the script of account onboading but while running this script We are getting an error that the safe doesn't exist. We have already provided the permission to the user. any suggestion for that?

**Comment by AssafMiron** [comment]
Hi,

Try running the script with -debug -verbose to see more information in the
log file
That might give a hint of why this fails

Regards,
Assaf

**Comment by GameChanger912** [comment]
Yes I have done that I am getting below response

DEBUG: Returning URL Encode of "safe name"
Safe "safe name"
Target Safe does not exist, No Safe creation requested - Will Skip account Creation
Skipping onboarding account Administrator@10.1.1.1 (CSV line: 1) into the Password Vault since safe does not exist and s

**Comment by AssafMiron** [comment]
The log says that "no safe creation was requested" check that you don't
have the switch of -nosafecreation in your call
You can also have a look at the parameters status in the log file (usually
the first line of each run of the script when running in verbose mode)

**Comment by GameChanger912** [comment]
Getting this response:

VERBOSE: Invoke-RestMethod -Uri
https://pvwaurl/PasswordVault/WebServices/PIMServices.svc/safe/safename -Method Get -Header
System.Collections.Hashtable -ContentType "application/json" -TimeoutSec 2700
VERBOSE: GET https://pvwaurl/PasswordVault/WebServices/PIMServices.svc/safe/safename with
0-byte payload
VERBOSE: Invoke-REST Response:
Safe safename does not exist

**Comment by GameChanger912** [comment]
Again I am getting the same error

**Comment by bab29** [comment]
Can you confirm you are going directly to the PVWA and not thru a load balancer? 

This is a known issue when a newly created safe is unavailable for use immediately after creation due to the cache not containing the newly created safe.

Can you confirm the version of PAS you are working with? Do you have the same issue when you are attempting to use the v2 interface for the creation and update?

**Comment by bab29** [comment]
There is a new version of this script out. Can you please try with the new version?

**Comment by bab29** [comment]
No response received

**Comment by jsweecl** [comment]
Hello. Just happen to see this thread which I'm having the same same issue on. The safe exists in the platform but the script says the Safe does not exist. I'm using the tenant admin for the login btw.
