### ISSUE TITLE
Cannot Validate argument on parameter 'PVWAURL'. The request was aborted: Could not create SSL/TLS channel.

### ISSUE THREAD

**Issue by SudSan** [cyberark/epv-api-scripts#225]
Hi AssafMiron,

When I run the Invoke-BulkAccountActions.ps1 to Verify the accounts, I'm getting an error below
Cannot Validate argument on parameter 'PVWAURL'. The request was aborted: Could not create SSL/TLS channel.

Thanks,
SudSan

**Comment by AssafMiron** [comment]
Hello SudSan,

Please run the script again with the switch of DisableSSLVerify
That should disable the SSL verification for the PowerShell session

Regards,
Assaf

**Comment by SudSan** [comment]
Hello Assaf,

I ran the script with DisableSSLVerify switch but no luck 

Thanks,
SudSan

**Comment by AssafMiron** [comment]
Hi SudSan,

Please comment line 32 in the script
This line:
[ValidateScript({Invoke-WebRequest -UseBasicParsing -DisableKeepAlive -Uri
$_ -Method 'Head' -ErrorAction 'stop' -TimeoutSec 30})]

That should solve the issue

Regards,
Assaf

**Comment by SudSan** [comment]
Hi Assaf,

Commented line 32 in the script and it worked. also ran the script with -DisableSSLVerify switch.. Many thanks !!! 👍 👍 👍 

Instead of prompting for CyberArk local user credentials, I want to include Rest API CCP user to fetch the password 
 Trying to fetch a password for the REST-API user from CyberArk (via CCP), and then authenticate into RestAPI using the retrieved credential

so I comment lines 636,637 and 638 
#$caption = "Bulk Account Actions"
#$msg = "Enter your PAS User name and Password ($AuthType)"; 
#$creds = $Host.UI.PromptForCredential($caption,$msg,"","")

And I've added below piece of code 

$response=""

$BaseUrl = "https:// CCP server host"

$AppID = xxx

$Safe = API User Safe

$ObJN = xxxxx (Rest API User Object Name)

$fetchpassword = "$BaseUrl/AIMWebService/api/Accounts?AppID=xxx&Safe=xxx&Object=xxx""

$response = Invoke-RestMethod -Uri $fetchpassword -UseDefaultCredentials

$creds = ($response.UserName, $response.Content)

When running the CCP fetch password and passing the user name and password to $creds, I'm getting error below

"There was an Error running bulk account actions. Error: Source:System.Management.Automation; Message: Cannot process argument transformation on parameter 'VaultCredentials' . username -> sourec.System.Management.Automation; Message: userName"

Do you know how can we achieve this?.

Thanks,
SudSan

**Comment by AssafMiron** [comment]
Hey SudSan,

That is a good code snippet 😊
I think you can try to convert the credentials you receive from string to
PSCredentials object (like the original script does) and then it should be
OK.

First you need to convert the password to secureString:

$password = ConvertTo-SecureString $response.content -AsPlainText -Force

Then you need to create the new PSCredentials object like this:
$creds = New-Object System.Management.Automation.PSCredential
($response.userName, $password)

Let us know if that solves the problem

Regards,
Assaf

**Comment by SudSan** [comment]
Hey Assaf,

It worked like a charm 😊 👍. Thanks a lot!!!
Is there a way to do the "Change password only in the Vault" and specify a specific password for target accounts?
Currently, the option is disabled if you select multiple accounts in classic UI. 

Thanks,
SudSan

**Comment by AssafMiron** [comment]
Hi SudSan,

You can use this REST API of updating the password in the vault:
https://
<IIS_Server_Ip>/passwordvault/api/Accounts/<AccountID>/Password/Update

More information here:
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/WebServices/ChangeCredentialsInVault.htm?tocpath=Developer%7CREST%20APIs%7CAccounts%7CAccount%20actions%7C_____12#URL


Regards,
Assaf
