### ISSUE TITLE
Update `PAS REST API.json` for Mockoon

### ISSUE THREAD

**Issue by aaearon** [cyberark/epv-api-scripts#228]
I stumbled across https://github.com/cyberark/epv-api-scripts/tree/main/Mock%20Server which provides `PAS REST API.json` and it is pretty great. The downside is that it has not been updated since mid 2020.

Before I start extending `PAS REST API.json` myself, is there a more recent version floating around that can be an update to what is in the repo now?

**Comment by AssafMiron** [comment]
Hi Tim,

Unfortunately this project was never truly complete and there was not
update to it since mid-2020
Happy that you find it useful, would be great if you can share a more
recent version if you end up using it and updating it

Regards,
Assaf
