### ISSUE TITLE
Example of how to pull static secrets for a safe with an auth flow ( any flow, but prefer client id and secret )

### ISSUE THREAD

**Issue by sbhorvatic** [cyberark/epv-api-scripts#249]
## Is your feature request related to a problem? Please describe.

I would like to see a flow of auth, pulling the safe and fetching a static secret because it is a common flow in today environment for applications to pull its own secrets.

For application to pull its own secrets

## Describe the solution you would like

I would like an example script to show the initial auth logon, fetch a static secret from vault, and output that secret.

**Comment by bab29** [comment]
This would be done via a Credential Provider or Conjure
