### ISSUE TITLE
Requirements for Safe-Management script

### ISSUE THREAD

**Issue by corsen55** [cyberark/epv-api-scripts#25]
Hello Team
Just in case anybody runs into this issue with running the script
The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ .\Safe-Management.ps1
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Safe-Management.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Safe-Management.ps1

The issue is related to TLS.  When the script runs against a hardened PVWA it does not negotiate TLS at all.  You will need to force the computer where running the script to use TLSv1.2.  FWIW, we were running .net4.7.2 on Windows 2016 and it would only connect on TLSv1.0)

Using Powershell
# set strong cryptography on 64 bit .Net Framework (version 4 and above)
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type Dword
# set strong cryptography on 32 bit .Net Framework (version 4 and above)
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

Thanks and great work!

**Comment by AssafMiron** [comment]
Added support for this in the latest script see #97
