### ISSUE TITLE
Safe-Management.ps1 is getting error when trying to just List

### ISSUE THREAD

**Issue by kaz-cyberark** [cyberark/epv-api-scripts#255]
## Summary

Getting this error when we use Safe-Management
==========
 .\Safe-Management.ps1 -PVWAURL "https://xxxxx.privilegecloud.cyberark.com/PasswordVault" -List
At C:\CYBR_Files\Safe Management\Safe-Management.ps1:882 char:81
+ ...  ($rMethodErr.message -like "*User or Group was not found.*") -or ($r ...
+                                                                 ~
Missing statement block after elseif ( condition ).
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingStatementBlock
==========

## Expected Results

Expected to be authorization request first, but no such request.

**Comment by phanimngr** [comment]
Hi @kaz-cyberark ,

I am also facing the same issue, please suggest if you sort out this.

**Comment by kaz-cyberark** [comment]
@phanimngr ,
Not really. I've not tested the updated one...
