### ISSUE TITLE
Logon Token is empty error

### ISSUE THREAD

**Issue by mrgitstone** [cyberark/epv-api-scripts#26]
Good afternoon

I have used the PGU tool to generate a PSM web connector. Now according to the manual I need to import it into pvwa. I am using the script "Import-ConnectionComponents.ps1" 

When I run the script with the necessary parameters in powershell to perform the import and then it asks me for credentials, I put the administrator credentials.

I get the following error : Logon token is empty - Cannot Login

PS C:\Users\jconchaz\Downloads> .\import.ps1 -PVWAURL https://pvwaaqp.cajaarequipa.pe/PasswordVault/v10/ -ConnectionComponentZipPath C:\Users\jconchaz\Downloads\PGU\ConnectionComponents\CiscoF
irePower.zip
Import Connection Component: Script Started

Logon Token is Empty - Cannot login

Please i need your help

**Comment by AssafMiron** [comment]
Hi @mrgitstone ,

The PVWA URL should not include /v10, only up to /PasswordVault
That should solve it

Regards,
Assaf
