### ISSUE TITLE
Need a readme or description of this script

### ISSUE THREAD

**Issue by Ethlas** [cyberark/epv-api-scripts#274]
https://github.com/cyberark/epv-api-scripts/blob/1b39071ea828e23be6a2b2580d6f802a536d1cd6/Migration%20via%20REST/Migrate.ps1#L12

Can we get a little more info about what this script does? Might also want to rename the script as it seems to only take parameter from account in environment a to environment b.

**Comment by bab29** [comment]
Currently this is being developed and used for one off. If you have questions about it's use and how to use it please reach directly out to me.

Once development is competed a full Readme.MD will be added.
