### ISSUE TITLE
Unable to add members/group to the newly  created safe. Please provide me the script for creating the safe & adding the members/group to it.

### ISSUE THREAD

**Issue by pradeepvennapu1** [cyberark/epv-api-scripts#284]
Hello all,
Unable to fulfill my requirement in creating the new safe & adding members/group to it via power shell script. Getting multiple errors with various trials. 
Please help me to provide the correct script to meet my requirement (Safe creation & adding members/group to it)

**Comment by Ethlas** [comment]
Hello @pradeepvennapu1 ,

Can you post the error message you are getting? I might be fixing it with the new branch but want to make sure.

Thanks.

**Comment by pradeepvennapu1** [comment]
Hello Ethan Sarikas,
Greetings!!!

Thanks for your response. 
Really I am getting multiple errors with my multiple trials, Hence I am sincerely requesting you to provide the PowerShell script along with CSV file. So that I can try with those in my Non Production environment for testing purpose

Regards,
Pradeep.

**Comment by pradeepvennapu1** [comment]
Hello Ethan Sarikas,
Greetings!!!

Thanks for your response.
Really I am getting multiple errors with my multiple trials, Hence I am sincerely requesting you to provide the PowerShell script along with CSV file. So that I can try with those in my Non Production environment for testing purpose

Regards,
Pradeep.

**Comment by Ethlas** [comment]
@pradeepvennapu1 , can you link a screenshot or a text of paper of your errors?
