### ISSUE TITLE
Seems it doesn't work with Cyberark version 10.2

### ISSUE THREAD

**Issue by Sunil20noi** [cyberark/epv-api-scripts#3]
Hi All,

I previously used "Accounts_Onboard_Utility.ps1" script with version 9.10 and 10.1 as well, It was working fine.
However recently i migrated to 10.2 and it seems script is not working any longer, every time i get below error message : 
Logon Token is empty : Cannot logon.

I have tried with Swagger UI with 10.2 and i am able to get token and perform further activities.
Has anyone tested this with version 10.2 yet ? 
Any help will be much appreciated in this regard.

**Comment by AssafMiron** [comment]
Hello @Sunil20noi ,

Thanks for letting us know.
Did you change the logon URL?
Or are you using the same as in the script?

Thanks,
Assaf

**Comment by Sunil20noi** [comment]
Hi Assaf,

I have tried with both with same result: 

1) Using the same as in script as https://X.X.X.X/PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logon

2) URL taken from Swagger and hardcoded in script as
https://X.X.X.X/PasswordVault/api/Auth/cyberark/Logon

Am i missing something here, has anything changed in 10.2 ?

Thanks
Sunil

**Comment by AssafMiron** [comment]
Hi @Sunil20noi ,
From your examples above, I assume that you are using IP Address and HTTPS.
Does your SSL certificate include the IP address of the server or only the name?
Try running the script in Verbose mode (just add -Verbose to the end of the command), you might see the following message:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
If this is the case, try running the script with a PVWA URL that matches the SSL certificate

Please update us if that solves this issue

Thanks,
Assaf

**Comment by AssafMiron** [comment]
Hey Sunil,

since you are using the new authentication module, the token response has change.
Can you please change the following line in the Get-LogonHeader function:
$logonToken = $logonResult.CyberArkLogonResult
to:
$logonToken = $logonResult

and try again?

Thanks,
Assaf

**Comment by Sunil20noi** [comment]
Hi Assaf,

After doing above changes it seems to be working. But let me carry out complete testing and i will let you know the outcome.

However, any idea how many calling API URL cyberark has changed, i could change logon and logoff url in script.

Regards
Sunil

**Comment by riturk** [comment]
Hi Sunil/Assaf,
I am new in scripting so please help me on this. I am getting bellow error.

Invoke-Rest : Not Found
At E:\DOC\Documentation\10.3\API\My API Script\epv-api-scripts-master\Create_User_and_Add_as_Owner_to_Safes.ps1:101 char:18
+ ... gonResult = Invoke-Rest -Command Post -Uri $URL_CyberArkLogon -Body $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Rest


Logon Token is Empty - Cannot login
