### ISSUE TITLE
account_onboard_utility throwing error with more than 1 duplicate check

### ISSUE THREAD

**Issue by ELANDJEA** [cyberark/epv-api-scripts#303]
## Summary

When one duplicate account is found, the script asks if a duplicate must be created
when more than one account is found, an error is thrown: "Error testing Account 'testacc4@adres4' existence. Error: Source:; Message: Get-Account: Error getting Account.         ->Source:; Message: Found 0 accounts in search - fix duplications"

## Steps to Reproduce

try to onboard an account (uid/secret/platform) that alsready exists more than 1 time in a safe

## Expected Results

just note that there are more than 0 accounts and ask if the new entry must also be onboarded....alle other logic in the scripts "get-account" function causes a wrong repsonse

## Actual Results

*A clear and concise description of what actually did happen. Include logs and
screens shots, whenever possible*

## Reproducible

   * [X] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

version of the script used 2.14

## Environment setup

pvwa 12.2
iis on windows 2016

**Comment by bab29** [comment]
When would you want to onboard accounts with the same username, address, and platform into the same safe to be automatically managed? Are you referring to cases when you are onboarding database accounts or something else with a additional field that would be unique in the safe?
