### ISSUE TITLE
Unable to use API's on Privilege Cloud

### ISSUE THREAD

**Issue by prayi** [cyberark/epv-api-scripts#313]
Hi Team,

I am trying to test the scripts and I am getting below error. Any help would be appreciated.
Below are few info:
Version : 12.6
Product: Privilege Cloud (SaaS)
Trying to run as LDAP authentication
Error: [ERROR]	Error Logging on. Error: Source:; Message: Get-LogonHeader: Internal Server Error
	->Source:Microsoft.PowerShell.Commands.Utility; Message: The remote server returned an error: (500) Internal Server Error.

**Comment by prayi** [comment]
Hi Team -We have Privilege Cloud as shared service and running 12.6 version. Attached the error message for your reference. Any help is appreciated.
![image](https://user-images.githubusercontent.com/45847983/211552540-2ca1ee60-13db-46dd-bcc9-eb9a2f983e72.png)

**Comment by bab29** [comment]
Privilege Cloud URL for REST is "https://<subdomain>.privilegecloud.cyberark.cloud/PasswordVault/ " which is different format then on-prem

**Comment by prayi** [comment]
Hi @bab29 - I tried with Privilege Cloud URL and getting attached error. Even i tried with account which exist in Identity portal but no luck.
![APIError](https://user-images.githubusercontent.com/45847983/217834986-79bf503f-8a37-46a5-907b-a10bd361617f.JPG)

**Comment by bab29** [comment]
If your PCloud instance is in SharedServices then you can not use a auth type of LDAP. You will need to pass the logonToken. 

You can review https://github.com/cyberark/epv-api-scripts/tree/main/Identity%20Authentication on how to generate a logonToken.
