### ISSUE TITLE
Identity Authentication - missing Add-ObjectDetail function

### ISSUE THREAD

**Issue by SpartoK** [cyberark/epv-api-scripts#321]
hi,
getting the following error when trying to use with pspas module, after using use-PASSession $header

Add-ObjectDetail : The term 'Add-ObjectDetail' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At [C:\Program](file:///C:/Program) Files\WindowsPowerShell\Modules\IdentityAuth\IdentityAuth.psm1:142 char:17
            } | Add-ObjectDetail -TypeName psPAS.CyberArk.Vault.Sessi ...
           ~~~~~~~~~~~~~~~~
    CategoryInfo         : ObjectNotFound: (Add-ObjectDetail:String) [], CommandNotFoundException
   FullyQualifiedErrorId : CommandNotFoundException

Would it be possible to add this dependency in the identity authentication module please?

**Comment by Ethlas** [comment]
There are two thoughts here, we can or create our own function or import WFTools. We can also ask psPete module to make it public for us to use.
