### ISSUE TITLE
Unable to update Account Properties with REST API script.

### ISSUE THREAD

**Issue by imittal312** [cyberark/epv-api-scripts#340]
Working on on-prem v12.6 cyberark environment.
Using the cyberark user to update account properties. Able to do it manually on PVWA but unable to do it via Script. Attaching the csv file used, powershell script used, error obtained.
I have created the csv file based on the below points:
![image](https://user-images.githubusercontent.com/129068713/234903099-763e19a3-ce6f-4c7c-bed8-5747ce9ad194.png)
![image](https://user-images.githubusercontent.com/129068713/234903145-99bbbca0-869e-4575-ba5e-d84bc5a72a11.png)
![image](https://user-images.githubusercontent.com/129068713/234903183-9dc9b30a-0f12-4296-9e3d-80fbb7460fc7.png)

Kindly help in troubleshooting.

**Comment by imittal312** [comment]
This is urgent. Could someone help me pls.

**Comment by imittal312** [comment]
@bab29 attached the log file. Kindly refer the latest timestamp logs. 
I have entered only those values in csv which needs to be updated (except safe and name parameters).
![image](https://github.com/cyberark/epv-api-scripts/assets/129068713/8e18a6e2-fc76-4b18-a913-e027016024f2)
[Account_Onboarding_Utility.log](https://github.com/cyberark/epv-api-scripts/files/11734108/Account_Onboarding_Utility.log)

**Comment by bab29** [comment]
According to the log file platformID has a tab at the end which is causing issues

/platformAccountProperties/platformID**\t**

I also noticed it was trying to set username to "" so I'm looking into that.
