### ISSUE TITLE
UpdateMember to alter member permissions on safe

### ISSUE THREAD

**Issue by PapaWig** [cyberark/epv-api-scripts#342]
I'm trying to use the safe-management.ps1 script to update a member's permissions on three safes.  Using my own account and a local CyberArk account both return the same error:
There was an error setting the membership for MemberName@domain.com on SAFE_NAME_HERE in the Vault. The error was:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable. (Not Found)

Both accounts have full permissions to the safes involved, 

Thoughts?

thanks!

**Comment by PapaWig** [comment]
Update:  Found that using a safe-management.ps1 file that was acquired last year (2.1.3) allows the permissions updates to complete successfully.  Using a version from 2.1.4 or later causes the error in my environment.

**Comment by bab29** [comment]
Please reproduce error with -verbose and attach log
