### ISSUE TITLE
Consistent handling of CSV delimiters

### ISSUE THREAD

**Issue by matiya** [cyberark/epv-api-scripts#358]
Related to #281: if one searches this repo for "Import-Csv $csvPath -Delimiter $delimiter" then I can see that there are different and not uniform way to derive the correct value for the delimiter.

For instance:

- https://github.com/cyberark/epv-api-scripts/blob/15deaad3ca413221465226d2b2e4adce3a0c281b/Linked%20Accounts/Link-Accounts.ps1#L632

- https://github.com/cyberark/epv-api-scripts/blob/15deaad3ca413221465226d2b2e4adce3a0c281b/Account%20Onboard%20Utility/Accounts_Onboard_Utility.ps1#L1505

I for one, find that it would be nice if one could pass the delimiter value as a parameter, but even if not it should be handled consistently so that I don't have to break into the debugger to find out how I should format the CSV.

**Comment by bab29** [comment]
There is a todo item to try and standardize the function and processes across all scripts. As these scripts have been donated by many different people that will have differences.
