### ISSUE TITLE
Account onboard utility error

### ISSUE THREAD

**Issue by iperhocks** [cyberark/epv-api-scripts#364]
I am receiving the below error when using the account onboard utility.

Note: We recently changed our MFA method.

Get-LogonHeader:
At C:\Scripts\epv-api-scripts-master\Account Onboard Utility\v10\Accounts_Onboard_Utility.ps1:1268 char:3
+         Throw $(New-Object System.Exception ("Get-LogonHeader: $($_.E ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Get-LogonHeader:

**Comment by bab29** [comment]
Can you provide the full command you are using? Feel free to scrub the PVWA URL
