### ISSUE TITLE
import-connectioncomponents.ps1 : Error importing the connection ID, Error: 

### ISSUE THREAD

**Issue by honorable2** [cyberark/epv-api-scripts#37]
I am trying to import psm connection using powershell .  Geting this error message when I ran it "import-connectioncomponents.ps1 : Error importing the connection ID, Error: Bad Request"
And error  when it get to this the line below. 
Invoke-RestMethod -Method Post -Uri $URL_CyberArkLogoff -Headers $logonHeader -ContentType "application/json" | Out-Null

My Cyberark version is V10.9.

Please help or advise, thanks.

**Comment by AssafMiron** [comment]
Hello @honorable2 ,

It looks like this is caused because you were not connected
Or you were disconnected from the session if the error is on this line
If this precedes you should contact CyberArk support as this is an example script and not something that is fully supported

Regards,
Assaf

**Comment by honorable2** [comment]
Thanks for the feedback AssafMiron, I was thinking there is something wrong with the "Invoke_RestMethod -Method Post......." I will run it again in Debug mode.
