### ISSUE TITLE
Logon Token is empty when running script for Privilege cloud

### ISSUE THREAD

**Issue by etebreezy** [cyberark/epv-api-scripts#378]
Hi,

I am trying to perform a bulk upload of safes using the script found in this link [https://github.com/cyberark/epv-api-scripts/tree/main/Safe%20Management]. My CyberArk environment is hosted on privilege cloud. Whenever I run the script, after authenticating, it throws the error: Logon token is empty. How can I run the script successfully on Privilege cloud?

Thanks

**Comment by bab29** [comment]
Hello,

Please ensure you are first getting a logon token using https://github.com/cyberark/epv-api-scripts/blob/main/Identity%20Authentication/IdentityAuth.psm1 then pass that token using -logonToken
