### ISSUE TITLE
CyberArk DLL

### ISSUE THREAD

**Issue by Gidiklf** [cyberark/epv-api-scripts#4]
Hi Assaf , 

How are you?

I want to ask you about PVWA url , what is it exactly?
Do i need any DLL for make the operation?

I try to create a safe in cyberark web in my company , with username and password .

Thank you ,
Best regards 

Gidi

**Comment by AssafMiron** [comment]
Hi,
This is not a DLL, we are using here REST API.
REST is based on HTTP commands, so the PVWA URL is the URL for the PVWA web site

Thanks,
Assaf
