### ISSUE TITLE
Logon Token is empty

### ISSUE THREAD

**Issue by nmangam001** [cyberark/epv-api-scripts#41]
Hello,

I am facing forbidden issue error while running the onboard account utility in privilege cloud for my client:

**.\account_onboard_utility.ps1 -PVWAURL https://xxx.privilegecloud.cyberark.com/PasswordVault -CsvPath .\Trial.csv -Create**

**Getting PVWA Credentials to start Onboarding Accounts
Exception Message: The remote server returned an error: (403) Forbidden.
Status Code: 403
Status Description: Forbidden
Logon Token is Empty - Cannot login**

I am using Cyberark pvwa version 11.3.

Please suggest.

**Comment by AssafMiron** [comment]
Hello @nmangam001 ,

forbidden issues are usually when you enter a wrong user name or password or if the server rejected your request
If you know that the entered credentials are correct, I suggest opening a support case

Regards,
Assaf
