### ISSUE TITLE
Get-SafeMembers function incorrect method

### ISSUE THREAD

**Issue by Maddog0057** [cyberark/epv-api-scripts#55]
On line 566 of Safe-Management.ps1 the incorrect rest method is used to retrieve Safe Members, it is POST when it should be GET, there is also a missing space between $accSafeMembersURL and -Method.

`$_safeMembers = $(Invoke-RestMethod -Uri $accSafeMembersURL-Method POST -Headers $g_LogonHeader -ContentType "application/json" -TimeoutSec 3600000 -ErrorAction "SilentlyContinue")`

Should be:

`$_safeMembers = $(Invoke-RestMethod -Uri $accSafeMembersURL -Method "Get" -Headers $g_LogonHeader -ContentType "application/json" -TimeoutSec 3600000 -ErrorAction "SilentlyContinue")`

**Comment by AssafMiron** [comment]
Hi @Maddog0057 ,

Thanks for pointing this out, I have updated the script as you can see in #57 

Thanks for helping us have better example scripts! :)
