### ISSUE TITLE
issue with Get-Account function in Account_Onboard_Utility for v10

### ISSUE THREAD

**Issue by FIMTooler** [cyberark/epv-api-scripts#6]
In the Get-Account function, the search result variable $_accounts isn't correctly looped through in the foreach statement.

$_accounts | write-host shows @{value=System.Object[]; count=1} on the console
$item | write-host shows the same value @{value=System.Object[]; count=1} on the console.

With single result the foreach should be updated to the following line.
foreach ($item in $_accounts.value)

*I have not tested this with multiple account results, only single account results.

**Comment by AssafMiron** [comment]
Thanks - Fixed!
