### ISSUE TITLE
Custom CPM is not honored

### ISSUE THREAD

**Issue by Jayk423** [cyberark/epv-api-scripts#68]
If EPV is configured with a differently-named CPM user (rather than PasswordManager) the script will error even if that CPM is defined in the csv. 

The default parameters on lines 338 & 278 seem to affect this. I've not dug into this much more than that. See attached error.
![Safe-Management](https://user-images.githubusercontent.com/37341416/83894039-c7226900-a71e-11ea-80e6-20d2566a5c12.jpg)

**Comment by AssafMiron** [comment]
Hello @Jayk423 ,

If you look at the safes-sample.csv - adding a custom managing CPM from CSV is not supported
If you want, you can do it using a single Safe and not using CSV

We could add it as an enhancement to the script in the future

Regards,
Assaf

**Comment by AssafMiron** [comment]
This request was added - would be great if you could validate that it works for you

**Comment by AssafMiron** [comment]
Any updates @Jayk423 ?

**Comment by AssafMiron** [comment]
Hey @Jayk423 ,

If there is any update we would appreciate if you can update here
for the meanwhile we are closing this issue

Thanks,
Assaf
