### ISSUE TITLE
What is the string required for 'Get-Accounts'

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/epv-api-scripts#72]
What string is required to run the 'GetAccounts.ps1' script? I have tried the following to get a list of accounts in a safe:

Get-Accounts.ps1 -PVWAURL https://115-pvwa001.south.local -List -SafeName TestSafe001

But get the following errors:

--------------------
 Get-Accounts.ps1 -PVWAURL https://115-pvwa001.south.local -List -SafeName _TestSafe001
Retrieving accounts...
C:\users\nathan.SOUTH\Desktop\epv-api-scripts-master\Get Accounts\Get-Accounts.ps1 : Exception of type 'Microsoft.PowerShell.Commands.WriteErrorException' was thrown.
At line:1 char:1
+ .\Get-Accounts.ps1 -PVWAURL https://115-pvwa001.south.local -List -Sa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-Accounts.ps1
 
Showing up to 50 accounts
Logoff Session...
Invoke-RestMethod : Specified value has invalid CRLF characters.
Parameter name: value
At C:\users\nathan.SOUTH\Desktop\epv-api-scripts-master\Get Accounts\Get-Accounts.ps1:296 char:5
+     Invoke-RestMethod -Method Post -Uri $URL_CyberArkLogoff -Headers  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
---------------

**Comment by AssafMiron** [comment]
Hey @NathTheDude 
I suspect that the Safe name that you passed had an extra carriage return (as the error states: Invoke-RestMethod : Specified value has invalid CRLF characters.)
I will try to update it in the script to go past such cases

**Comment by NathTheDude** [comment]
Hey @AssafMiron,

Thanks for looking at this, apologies it was my mistake. In my command I did not add the '/passwordvault' to the ends of my pvwa address. Providing the full pvwa address resolves the issue.
