### ISSUE TITLE
Issue in loop within Update - Account Onboarding Utility v10

### ISSUE THREAD

**Issue by FIMTooler** [cyberark/epv-api-scripts#8]
I've submitted a couple issues not long ago.  Thanks for the quick turn around on those by the way.  It lead me to thinking there was something not right with the update functionality of the script.  It doesn't seem to have been tested.

Thus now that I have a bit of time to dig in I've discovered there's an issue with the below foreach loop and the $sProp variable.  $sProp.Key doesn't exist.  Seems like it should be $sProp.Name in this case.  That should then match it up with the WebServices SDK guide of supplying the attribute name in the Path value.

A nice to have while in this loop would be a check against list of supported properties that can be updated per the SDK guide.  Error updating property X not supported logged to file\console.

Foreach($sProp in $s_Account.PSObject.Properties)
{
    "sProp name: $($sProp.Name)" | Write-Host -ForegroundColor Red
    "sProp value: $($sProp.Value)" | Write-Host -ForegroundColor Red
    "objAccount value: $($objAccount.($sProp.Name))" | Write-Host -ForegroundColor Red
	If($objAccount.$($sProp.Name) -ne $sProp.Value)
	{
		$_bodyOp = "" | select "op", "path", "value"
		$_bodyOp.op = "replace"
		$_bodyOp.path = "/"+$sProp.Key
		$_bodyOp.value = $objAccount.$($sProp.Key)
		$s_AccountBody += $_bodyOp
	}
    "************" | Write-Host
}

**Comment by AssafMiron** [comment]
Hello @FIMTooler ,
I have now changed the update area and It should be correct now
I would appreciate if you can confirm

**Comment by AssafMiron** [comment]
Script updated and fixed
