### ISSUE TITLE
Logon Token is Empty - Cannot login

### ISSUE THREAD

**Issue by BrogieB** [cyberark/epv-api-scripts#85]
for get-platformdetails.ps1, getting 

"Logon Token is Empty - Cannot login"

**Comment by BrogieB** [comment]
going against version 11.4

**Comment by AssafMiron** [comment]
Hello @BrogieB ,

This error can result of several things
Please see #26  or #41  that had similar issues
And also make sure you are using a valid SSL certificate and the correct TLS settings

Let me know if that helps,
Assaf

**Comment by AssafMiron** [comment]
Hello @BrogieB ,
Any update?
I am closing this issue for now, but feel free to re-open if problem was not resolved

Regards,
Assaf

**Comment by AbdullaRifai** [comment]
& ./Accounts_Onboard_Utility.ps1 -PVWAURL "10.0.0.1/PasswordVault" -Delete -CsvPath "./CyberArk Cleanup non-operational - Copy.csv"

**Hey all, I have done it until Password Vault but face this issue:**

Error Message: Unable to connect to the remote server
Exception Message: Unable to connect to the remote server
Status Code:
Status Description:
Get-LogonHeader: Logon Token is Empty - Cannot login
At C:\path\Accounts_Onboard_Utility.ps1:1198 char:3
+         Throw "Get-LogonHeader: Logon Token is Empty - Cannot login"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Get-LogonHeader... - Cannot login:String) [], RuntimeException
    + FullyQualifiedErrorId : Get-LogonHeader: Logon Token is Empty - Cannot login

**Although I get prompted to sign on and enter my login information.**
