### ISSUE TITLE
ConvertTo-Json issue - Accounts_Onboard_Utility v10

### ISSUE THREAD

**Issue by FIMTooler** [cyberark/epv-api-scripts#9]
After much time spent digging into why account updates weren't working, it seems the below line is somewhat incorrect.  Although the output looks almost identical, if there is only one operation in the $s_AccountBody array, the $restBody will be missing beginning and end [ ].

$restBody = $s_AccountBody | ConvertTo-Json -depth 5

{
    "op":  "replace",
    "path":  "/name",
    "value":  "OlderName"
}

Adjusting to this seems to work correctly even if there's only one object in the array.

 $restBody = ConvertTo-Json @($s_AccountBody) -depth 5

[
    {
        "op":  "replace",
        "path":  "/name",
        "value":  "OlderName"
    }
]

**Comment by AssafMiron** [comment]
Hi @FIMTooler ,

Thanks for your comments and testing.
I updated the code to reflect this change

Thanks,
Assaf
