### ISSUE TITLE
Limit Domain Access To and ExtraPass Values

### ISSUE THREAD

**Issue by jonnadulasudhakar** [cyberark/epv-api-scripts#94]
Hi,

I have updated one account to change the **NAME** property. I have removed RemoteMachineAddress and RestrictMachinesAccesstoList fileds in the CSV File. Now all accounts are updated with Limit Domain Access TO and unable to remove the property. Please advise.

Even after creating the extra pass values in the platform, we are unable to associate extrapass1 and extrapass3 values to the account.

Also, let us know what are the mandatory parameters to update any property in the account. 

Thanks,
Sudhakar

**Comment by AssafMiron** [comment]
Hi @jonnadulasudhakar 
I have updated the script to try and fix the issue you are experiencing with the RemoteMachineAddress

For the Linked Accounts, please see this CyberArk KB: "https://cyberark-customers.force.com/s/article/Add-Reconcile-and-Login-Accounts-to-an-Account-using-V10-REST-API"

**Comment by jonnadulasudhakar** [comment]
The current script will help to fix the problem? Please advise.

**Comment by AssafMiron** [comment]
Hi,
It should
Did you try using the UI to fix the issue?
If problem is not fixed using the script or the UI, I think you would need to open a case to CyberArk support

**Comment by jonnadulasudhakar** [comment]
I have tried removing it on the UI interface. However, I don't have option to remove on the platform. Thanks for the information and I will log a case with CyberArk on this.

The link https://cyberark-customers.force.com/s/article/Add-Reconcile-and-Login-Accounts-to-an-Account-using-V10-REST-API is showing the commands. I am not sure how to incorporate these lines into your onboarding script. Please advise which line I can insert the commands to check.

The reconciliation account and safe will vary depending on the onboarding design. We want to pull the reconciliation safe and account from the CSV file. I am using PACLI script for reconciliation. however, if the CSV file will allow the same functionality don't need to use two separate scripts to onboard.

PACLI Script:
PACLI ADDFILECATEGORY SAFE=%1 FOLDER=Root FILE=%2 CATEGORY="ExtraPass3Safe" VALUE=%3
PACLI ADDFILECATEGORY SAFE=%1 FOLDER=Root FILE=%2 CATEGORY="ExtraPass3Folder" VALUE="Root"
PACLI ADDFILECATEGORY SAFE=%1 FOLDER=Root FILE=%2 CATEGORY="ExtraPass3Name" VALUE=%4

PACLI ADDFILECATEGORY SAFE=%1 FOLDER=Root FILE=%2 CATEGORY="ResetImmediately" VALUE=ReconcileTask
PACLI ADDFILECATEGORY SAFE=%1 FOLDER=Root FILE=%2 CATEGORY="RetriesCount" VALUE="-1"


Thanks,
Sudhakar

**Comment by AssafMiron** [comment]
Hi,

actually you don't need to edit the script
just make sure you complete step 1 in the article:
Step 1 - add the properties to the platform
In "Administration - Platform Management" select the platform that is used for the accounts.
Select Edit to edit the platform.
Expand "UI & Workflows"
Expand Properties
Right click on "Optional" and select "Add Property" to add Optional Properties to the platform. Add the following six properties:
     Name - ExtraPass1Folder,  DisplayName - Logon Account Folder
     Name - ExtraPass1Name, DisplayName - Logon Account Name
     Name - ExtraPass1Safe, DisplayName - Logon Account Safe
     Name - ExtraPass3Folder, DisplayName - Reconcile Account Folder
     Name - ExtraPass3Name, DisplayName - Reconcile Account Name
     Name - ExtraPass3Safe. DisplayName - Reconcile Account Safe

and add the relevant fields to the csv with their appropriate name
for example, add the following columns:
ExtraPass3Folder,ExtraPass3Name,ExtraPass3Safe
and for each line you need a reconcile account for, make sure to propagate the relevant data
