### ISSUE TITLE
Dependent Account onboard utility 

### ISSUE THREAD

**Issue by p-yadav** [cyberark/epv-api-scripts#95]
Unable to the onboard dependent account using API. Below are the details.

PS C:\epv-api-scripts-master\Dependent Account onboard utility> .\Onboard-DependentAccountsFromCSV.ps1 -PVWAURL "https://pvwa.cyberark.com/PasswordVault/"  -CsvPath .\dependentAccounts.csv -Debug -Verbose
DEBUG: Setting script to use TLS 1.2
DEBUG: Trying to validate URL: https://pvwa.cyberark.com/PasswordVault
VERBOSE: HEAD https://pvwa.cyberark.com/PasswordVault with 0-byte payload
VERBOSE: received 17-byte response of content type 
=======================================
Welcome to Accounts Dependencies Onboard Utility
------------------------------------
Getting PVWA Credentials to start Onboarding Dependencies
VERBOSE: Invoke-RestMethod -Uri https://pvwa.cyberark.com/PasswordVault//api/auth/cyberark/Logon -Method Post -Header  -ContentType "application/json" -Body {
    "password":  "****%gyDbWMfy",
    "username":  "cyberark"
} -TimeoutSec ****6000
VERBOSE: POST https://pvwa.cyberark.com/PasswordVault//api/auth/cyberark/Logon with -1-byte payload
Exception Message: The remote server returned an error: (409) Conflict.
Status Code: 409
Status Description: Conflict
VERBOSE: Invoke-REST Response: 
Logon Token is Empty - Cannot login

**Comment by AssafMiron** [comment]
Hello @p-yadav 
Can it be that the user that you are using is currently logged on in PrivateArk client or not logged off from another script?
Can you try to make sure that this user logged off (for example by logging in to PrivateArk client and then logging off) and try the script again?

**Comment by p-yadav** [comment]
Hi Assaf,

Thanks, that user is just used for onboarding of user account via API.
It’s only used by me for API purposes.

Thanks
Prem Yadav

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AssafMiron** [comment]
Hi @p-yadav 
Did you try looking in the PVWA WebServices log in the PVWA server?
Maybe it will give more details, at the moment from the script logs I cannot get more ideas other than the above

**Comment by p-yadav** [comment]
Hi Assaf,

I don’t have access to the server at the moment.
I will contact the respective team and get back to you

Thanks
Prem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AssafMiron** [comment]
Hello @p-yadav ,
Any updates?

**Comment by p-yadav** [comment]
Hi Assaf,

Still getting the same error, moved to manual on boarding.

Thanks
Prem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AssafMiron** [comment]
Hello @p-yadav ,
The script was recently updated with a fix that might be related to your error
do you mind testing again?

Regards,
Assaf

**Comment by p-yadav** [comment]
Hi Assaf,

Thanks, I don’t have access to customer environment as the project is delivered.

Thanks
Prem


Thanks
PY
________________________________
